robot:
  type: so100

control:
  type: record
  fps: 30 
  single_task: "make a burger" 
  multi_task: true
  task_index: 1
  repo_id: tgossin/burger 
  tags:
    - tutorial
  warmup_time_s: 5
  episode_time_s: 60 
  reset_time_s: 10 
  num_episodes: 20
  push_to_hub: false
  display_data: true
  resume: true